[project]
name = "cortexlib"
version = "0.2.0"
git_repo_url = "https://github.com/oraqlle/cortexlib/"
git_default_branch = "main"

[paths]
compile_commands = "build/compile_commands.json"
output_dir = "docs/hdoc"

[includes]
paths = []
use_system_includes = true

[ignore]
paths = [
  "/tests/",
  "/subprojects/",
]

[pages]
homepage = "README.md"